### ISSUE TITLE
Please get into the Gentoo layman registry

### ISSUE THREAD

**Issue by hartwork** [ldc-developers/gentoo-overlay#12]
Hi!

https://github.com/ldc-developers/ldc#from-a-pre-built-package reads `layman -a ldc` but it does not seem to be in [the layman registry](https://github.com/gentoo/api-gentoo-org/blob/master/files/overlays/repositories.xml). Please file a pull request at https://github.com/gentoo/api-gentoo-org for addition. Thanks!

Best, Sebastian

**Comment by biocyberman** [comment]
There is this active overlay already: https://github.com/gentoo/dlang . And it is quite up to date and has clear advantages of offering `dmd`, `gdc`, `ldc` and serveral other tools written in `D`. 

So I would suggest leaving the overlay part to the maintainer(s) of that overlay. LDC developers can send PR to them instead of maintaining this repo.

**Comment by dnadlinger** [comment]
@redstar: How do we kill of this repo gracefully then?

**Comment by redstar** [comment]
First, we should update README.md as this caused this issue. Then I can delete the repo.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
